config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :account do
    root :to => 'account#edit'
    resource :account, :only => [:edit, :update], :controller => :account do
      member do
        get 'regenerate'
      end
    end
    resources :users
  end

  namespace :content do
    root :to => 'albums#index'
    resources :albums
    resources :blurbs
    resources :employees
    resources :lists
    resources :maps
    resources :navs
    resources :posts
    resources :testimonials
  end

  namespace :dashboard do
    root :to => 'overview#index'
    get 'overview' => 'overview#index'
    resources :activities, :only => [:index]
  end

  get 'login' => 'authentication#login'
  post 'login' => 'authentication#login_create'
  get 'logout' => 'authentication#login_destroy'
  get 'recover' => 'authentication#recover'
  post 'recover' => 'authentication#recover_process'
  get 'reset' => 'authentication#reset'
  post 'reset' => 'authentication#reset_process'

  root :to => 'dashboard/overview#index'

end

app/models/activity.rb
class Activity
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :action, :type => String
  
  validates_presence_of :action
  
  default_scope ->{ where(:account_id => Account.current_id) }
  
  belongs_to :account
  belongs_to :trackable, :polymorphic => true
  belongs_to :user
end

app/models/map.rb
class Map
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :center,      :type => String
  field :identifier,  :type => String
  field :zoom,        :type => Integer, :default => 13
  
  validates_presence_of :center, :zoom
  
  default_scope ->{ where(:account_id => Account.current_id) }
  
  belongs_to  :account
end

app/controllers/content/maps_controller.rb
class Content::MapsController < ApplicationController
  before_filter :authenticate
  
  def index
    @maps = Map.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @map = Map.find(params[:id])
    
    render
  end
  
  def new
    @map = Map.new(:account => current_account)
    
    render
  end
  
  def create
    @map = Map.new(params[:map])
    
    if @map.save
      track_activity @map
      redirect_to content_maps_path, :notice => 'map created successfully!'
    else
      render :new
    end
  end

  def edit
    @map = Map.find_by(:id => params[:id])
    
    if @map
      render :edit
    else
      redirect_to content_maps_path
    end
  end
  
  def update
    @map = Map.find_by(:id => params[:id])
    
    if @map.update_attributes(params[:map])
      track_activity @map
      redirect_to edit_content_map_path(@map), :notice => 'map updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @map = Map.find_by(:id => params[:id])
    track_activity @map
    @map.destroy
    
    redirect_to content_maps_path, :notice => 'map deleted successfully!'
  end
end

app/controllers/dashboard/activities_controller.rb
class Dashboard::ActivitiesController < ApplicationController
  before_filter :authenticate
  
  def index
    @activities = Activity.desc(:created_at).limit(15)
    
    respond_to do |format|
      format.html
    end
  end
end

app/views/dashboard/activities/map/_create.html.haml
%span{:class => "info #{activity.trackable_type.underscore}"}
  = link_to raw("<em>#{activity.user.username}</em>"), account_user_path(activity.user)
  created
  = activity.trackable_type.downcase
  - unless activity.trackable.nil?
    = link_to activity.trackable.center, content_map_path(activity.trackable)
  - else
    that has since been deleted
%span{:class => 'date'}
  = "#{time_ago_in_words(activity.created_at)} ago"

app/views/dashboard/activities/map/_destroy.html.haml
%span{:class => "info #{activity.trackable_type.underscore}"}
  = link_to raw("<em>#{activity.user.username}</em>"), account_user_path(activity.user)
  deleted
  = activity.trackable_type.downcase
%span{:class => 'date'}
  = "#{time_ago_in_words(activity.created_at)} ago"

app/views/dashboard/activities/map/_update.html.haml
%span{:class => "info #{activity.trackable_type.underscore}"}
  = link_to raw("<em>#{activity.user.username}</em>"), account_user_path(activity.user)
  updated
  = activity.trackable_type.downcase
  - unless activity.trackable.nil?
    = link_to activity.trackable.center, content_map_path(activity.trackable)
  - else
    that has since been deleted
%span{:class => 'date'}
  = "#{time_ago_in_words(activity.created_at)} ago"