config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :account do
    root :to => 'account#edit'
    resource :account, :only => [:edit, :update], :controller => :account do
      member do
        get 'regenerate'
      end
    end
    resources :users
  end

  namespace :content do
    root :to => 'albums#index'
    resources :albums
    resources :blurbs
    resources :employees
    resources :lists
    resources :maps
    resources :navs
    resources :posts
    resources :testimonials
  end

  namespace :dashboard do
    root :to => 'overview#index'
    get 'overview' => 'overview#index'
    resources :activities, :only => [:index]
  end

  get 'login' => 'authentication#login'
  post 'login' => 'authentication#login_create'
  get 'logout' => 'authentication#login_destroy'
  get 'recover' => 'authentication#recover'
  post 'recover' => 'authentication#recover_process'
  get 'reset' => 'authentication#reset'
  post 'reset' => 'authentication#reset_process'

  root :to => 'dashboard/overview#index'

end

app/models/list.rb
class List
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :identifier,  :type => String
  field :title,       :type => String
  
  validates_presence_of :title
  
  default_scope ->{ where(:account_id => Account.current_id) }
  
  belongs_to  :account
  embeds_many :bullets, :cascade_callbacks => true
  
  accepts_nested_attributes_for :bullets, :allow_destroy => true
end

app/controllers/content/albums_controller.rb
class Content::AlbumsController < ApplicationController
  before_filter :authenticate
  
  def index
    @albums = Album.asc(:index)
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @album = Album.find(params[:id])
    
    render
  end
  
  def new
    @album = Album.new(:account => current_account)
    
    render
  end
  
  def create
    @album = Album.new(params[:album])
    
    if @album.save
      track_activity @album
      redirect_to content_albums_path, :notice => 'album created successfully!'
    else
      render :new
    end
  end

  def edit
    @album = Album.find_by(:id => params[:id])
    
    if @album
      render :edit
    else
      redirect_to content_albums_path
    end
  end
  
  def update
    @album = Album.find_by(:id => params[:id])
    
    if @album.update_attributes(params[:album])
      track_activity @album
      redirect_to edit_content_album_path(@album), :notice => 'album updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @album = Album.find_by(:id => params[:id])
    track_activity @album
    @album.destroy
    
    redirect_to content_albums_path, :notice => 'album deleted successfully!'
  end
end

app/controllers/content/blurbs_controller.rb
class Content::BlurbsController < ApplicationController
  before_filter :authenticate
  
  def index
    @blurbs = Blurb.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @blurb = Blurb.find(params[:id])
    
    render
  end
  
  def new
    @blurb = Blurb.new(:account => current_account)
    
    render
  end
  
  def create
    @blurb = Blurb.new(params[:blurb])
    
    if @blurb.save
      track_activity @blurb
      redirect_to content_blurbs_path, :notice => 'blurb created successfully!'
    else
      render :new
    end
  end

  def edit
    @blurb = Blurb.find_by(:id => params[:id])
    
    if @blurb
      render :edit
    else
      redirect_to content_blurbs_path
    end
  end
  
  def update
    @blurb = Blurb.find_by(:id => params[:id])
    
    if @blurb.update_attributes(params[:blurb])
      track_activity @blurb
      redirect_to edit_content_blurb_path(@blurb), :notice => 'blurb updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @blurb = Blurb.find_by(:id => params[:id])
    track_activity @blurb
    @blurb.destroy
    
    redirect_to content_blurbs_path, :notice => 'blurb deleted successfully!'
  end
end

app/controllers/content/employees_controller.rb
class Content::EmployeesController < ApplicationController
  before_filter :authenticate
  
  def index
    @employees = Employee.asc(:index)
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @employee = Employee.find(params[:id])
    
    render
  end
  
  def new
    @employee = Employee.new(:account => current_account)
    
    render
  end
  
  def create
    @employee = Employee.new(params[:employee])
    
    if @employee.save
      track_activity @employee
      redirect_to content_employees_path, :notice => 'employee created successfully!'
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find_by(:id => params[:id])
    
    if @employee
      render :edit
    else
      redirect_to content_employees_path
    end
  end
  
  def update
    @employee = Employee.find_by(:id => params[:id])
    
    if @employee.update_attributes(params[:employee])
      track_activity @employee
      redirect_to edit_content_employee_path(@employee), :notice => 'employee updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @employee = Employee.find_by(:id => params[:id])
    track_activity @employee
    @employee.destroy
    
    redirect_to content_employees_path, :notice => 'employee deleted successfully!'
  end
end

app/controllers/content/lists_controller.rb
class Content::ListsController < ApplicationController
  before_filter :authenticate
  
  def index
    @lists = List.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @list = List.find(params[:id])
    
    render
  end
  
  def new
    @list = List.new(:account => current_account)
    
    render
  end
  
  def create
    @list = List.new(params[:list])
    
    if @list.save
      track_activity @list
      redirect_to content_lists_path, :notice => 'list created successfully!'
    else
      render :new
    end
  end

  def edit
    @list = List.find_by(:id => params[:id])
    
    if @list
      render :edit
    else
      redirect_to content_lists_path
    end
  end
  
  def update
    @list = List.find_by(:id => params[:id])
    
    if @list.update_attributes(params[:list])
      track_activity @list
      redirect_to edit_content_list_path(@list), :notice => 'list updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @list = List.find_by(:id => params[:id])
    track_activity @list
    @list.destroy
    
    redirect_to content_lists_path, :notice => 'list deleted successfully!'
  end
end

app/controllers/content/maps_controller.rb
class Content::MapsController < ApplicationController
  before_filter :authenticate
  
  def index
    @maps = Map.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @map = Map.find(params[:id])
    
    render
  end
  
  def new
    @map = Map.new(:account => current_account)
    
    render
  end
  
  def create
    @map = Map.new(params[:map])
    
    if @map.save
      track_activity @map
      redirect_to content_maps_path, :notice => 'map created successfully!'
    else
      render :new
    end
  end

  def edit
    @map = Map.find_by(:id => params[:id])
    
    if @map
      render :edit
    else
      redirect_to content_maps_path
    end
  end
  
  def update
    @map = Map.find_by(:id => params[:id])
    
    if @map.update_attributes(params[:map])
      track_activity @map
      redirect_to edit_content_map_path(@map), :notice => 'map updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @map = Map.find_by(:id => params[:id])
    track_activity @map
    @map.destroy
    
    redirect_to content_maps_path, :notice => 'map deleted successfully!'
  end
end

app/controllers/content/navs_controller.rb
class Content::NavsController < ApplicationController
  before_filter :authenticate
  
  def index
    @navs = Nav.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @nav = Nav.find(params[:id])
    
    render
  end
  
  def new
    @nav = Nav.new(:account => current_account)
    
    render
  end
  
  def create
    @nav = Nav.new(params[:nav])
    
    if @nav.save
      track_activity @nav
      redirect_to content_navs_path, :notice => 'nav created successfully!'
    else
      render :new
    end
  end

  def edit
    @nav = Nav.find_by(:id => params[:id])
    
    if @nav
      render :edit
    else
      redirect_to content_navs_path
    end
  end
  
  def update
    @nav = Nav.find_by(:id => params[:id])
    
    if @nav.update_attributes(params[:nav])
      track_activity @nav
      redirect_to edit_content_nav_path(@nav), :notice => 'nav updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @nav = Nav.find_by(:id => params[:id])
    track_activity @nav
    @nav.destroy
    
    redirect_to content_navs_path, :notice => 'nav deleted successfully!'
  end
end

app/controllers/content/posts_controller.rb
class Content::PostsController < ApplicationController
  before_filter :authenticate
  
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @post = Post.find(params[:id])
    
    render
  end
  
  def new
    @post = Post.new(:account => current_account)
    
    render
  end
  
  def create
    @post = Post.new(params[:post])
    
    if @post.save
      track_activity @post
      redirect_to content_posts_path, :notice => 'post created successfully!'
    else
      render :new
    end
  end

  def edit
    @post = Post.find_by(:id => params[:id])
    
    if @post
      render :edit
    else
      redirect_to content_posts_path
    end
  end
  
  def update
    @post = Post.find_by(:id => params[:id])
    
    if @post.update_attributes(params[:post])
      track_activity @post
      redirect_to edit_content_post_path(@post), :notice => 'post updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @post = Post.find_by(:id => params[:id])
    track_activity @post
    @post.destroy
    
    redirect_to content_posts_path, :notice => 'post deleted successfully!'
  end
end

app/controllers/content/testimonials_controller.rb
class Content::TestimonialsController < ApplicationController
  before_filter :authenticate
  
  def index
    @testimonials = Testimonial.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @testimonial = Testimonial.find(params[:id])
    
    render
  end
  
  def new
    @testimonial = Testimonial.new(:account => current_account)
    
    render
  end
  
  def create
    @testimonial = Testimonial.new(params[:testimonial])
    
    if @testimonial.save
      track_activity @testimonial
      redirect_to content_testimonials_path, :notice => 'testimonial created successfully!'
    else
      render :new
    end
  end

  def edit
    @testimonial = Testimonial.find_by(:id => params[:id])
    
    if @testimonial
      render :edit
    else
      redirect_to content_testimonials_path
    end
  end
  
  def update
    @testimonial = Testimonial.find_by(:id => params[:id])
    
    if @testimonial.update_attributes(params[:testimonial])
      track_activity @testimonial
      redirect_to edit_content_testimonial_path(@testimonial), :notice => 'testimonial updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @testimonial = Testimonial.find_by(:id => params[:id])
    track_activity @testimonial
    @testimonial.destroy
    
    redirect_to content_testimonials_path, :notice => 'testimonial deleted successfully!'
  end
end

app/views/content/lists/_bullet_fields.html.haml
%fieldset
  %div
    = f.label :title, 'Title'
    = f.text_field :title
  %div
    = f.label :index, 'Index'
    = f.number_field :index
  %div
    = f.label :content, 'Content'
    = f.text_area :content, :rows => 3
  %div
    = f.label :_destroy, 'Remove'
    = f.hidden_field :_destroy
    = link_to 'Remove', '#', :class => 'remove_fields button'

app/views/content/lists/_form.html.haml
= render :partial => 'shared/error', :locals => {:object => list}
= form_for list, :url => url do |f|
  %div{:id => 'list', :class => 'content_div'}
    %h2 List
    %hr
    %div.hidden
      = f.hidden_field :account_id
    %div
      = f.label :title, 'Title'
      = f.text_field :title
  %div{:id => 'bullets', :class => 'content_div'}
    .heading
      %h2 Bullets
      %nav
        = link_to_add_fields 'Add bullet', f, :bullets
    %hr
    .fields
      = f.fields_for :bullets do |b|
        = render 'bullet_fields', :f => b
  %div{:id => 'administrator', :class => 'content_div'}
    %h2 Administrator
    %hr
    %div
      = f.label :identifier, 'Identifier'
      = f.text_field :identifier

app/views/content/lists/edit.html.haml
%section{:id => 'content_lists_edit'}
  .sidebar
    .sidebar_header
      %h2 Edit List
    .sidebar_nav
      %nav.content_nav
        %div{:class => 'selected'}
          %a{:href => '#list'} List
        %div
          %a{:href => '#bullets'} Bullets
        - if current_user.administrator?
          %div
            %a{:href => '#administrator'} Administrator
    .sidebar_buttons
      = submit_tag 'Save', :form => "edit_list_#{@list.id}"
      = link_to 'Back to lists', content_lists_path
  .content
    = render :partial => 'form', :locals => {:list => @list, :url => content_list_path}

app/views/content/lists/index.html.haml
%section{:id => 'content_lists_index'}
  .heading
    %h2 Lists
    %nav
      = link_to 'Create new list', new_content_list_path
  %hr
  /= render :partial => 'shared/filter', :locals => {:objects => @lists, :search => @search, :path => :content_lists_path, :recent => true}
  - unless @lists.empty?
    %table
      %thead
        %tr
          %th Identifier
          %th Title
          %th View
          %th Edit
          %th Delete
      %tbody
        - @lists.each do |list|
          %tr
            %td= list.identifier
            %td= list.title
            %td
              = link_to 'View', content_list_path(list)
            %td
              = link_to 'Edit', edit_content_list_path(list)
            %td
              = link_to 'Delete', content_list_path(list), :confirm => 'Are you sure?', :method => :delete
  - else
    %p.center No lists found
  /= render :partial => 'shared/pagination', :locals => {:objects => @lists, :search => @search, :path => :content_lists_path}

app/views/content/lists/new.html.haml
%section{:id => 'content_lists_new'}
  .sidebar
    .sidebar_header
      %h2 New List
    .sidebar_nav
      %nav.content_nav
        %div{:class => 'selected'}
          %a{:href => '#list'} List
        %div
          %a{:href => '#bullets'} Bullets
        - if current_user.administrator?
          %div
            %a{:href => '#administrator'} Administrator
    .sidebar_buttons
      = submit_tag 'Save', :form => 'new_list'
      = link_to 'Back to lists', content_lists_path
  .content
    = render :partial => 'form', :locals => {:list => @list, :url => content_lists_path}

app/views/content/lists/show.html.haml
%section{:id => 'content_lists_show'}
  .sidebar
    .sidebar_header
      %h2 View List
    .sidebar_nav
      %nav.content_nav
        %div{:class => 'selected'}
          %a{:href => '#list'} List
        %div
          %a{:href => '#bullets'} Bullets
    .sidebar_buttons
      = link_to 'Edit', edit_content_list_path(@list)
      = link_to 'Back to lists', content_lists_path
  .content
    %div{:id => 'list', :class => 'content_div'}
      %h2 List
      %hr
      %div
        %dl
          %dt Identifier
          %dd= @list.identifier
      %div
        %dl
          %dt Title
          %dd= @list.title
    %div{:id => 'bullets', :class => 'content_div'}
      %h2 Bullets
      %hr
      - @list.bullets.each do |bullet|
        %div
          %dl
            %dt Title
            %dd= bullet.title
        %div
          %dl
            %dt Index
            %dd= bullet.index
        %div
          %dl
            %dt Content
            %dd= bullet.content