config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :account do
    root :to => 'account#edit'
    resource :account, :only => [:edit, :update], :controller => :account do
      member do
        get 'regenerate'
      end
    end
    resources :users
  end

  namespace :content do
    root :to => 'albums#index'
    resources :albums
    resources :blurbs
    resources :employees
    resources :lists
    resources :maps
    resources :navs
    resources :posts
    resources :testimonials
  end

  namespace :dashboard do
    root :to => 'overview#index'
    get 'overview' => 'overview#index'
    resources :activities, :only => [:index]
  end

  get 'login' => 'authentication#login'
  post 'login' => 'authentication#login_create'
  get 'logout' => 'authentication#login_destroy'
  get 'recover' => 'authentication#recover'
  post 'recover' => 'authentication#recover_process'
  get 'reset' => 'authentication#reset'
  post 'reset' => 'authentication#reset_process'

  root :to => 'dashboard/overview#index'

end

app/models/activity.rb
class Activity
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :action, :type => String
  
  validates_presence_of :action
  
  default_scope ->{ where(:account_id => Account.current_id) }
  
  belongs_to :account
  belongs_to :trackable, :polymorphic => true
  belongs_to :user
end

app/models/employee.rb
class Employee
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  
  field :email,           :type => String
  field :index,           :type => Integer, :default => 0
  field :name,            :type => String
  field :subtitle,        :type => String
  field :title,           :type => String
  
  attr_accessor :image_url, :image_delete
  
  before_validation { image.clear if image_delete == '1' }
  
  has_mongoid_attached_file :image,
    :default_url => '/assets/missing/:attachment/missing_:style.png'
  
  validates_presence_of     :name, :title
  validates_presence_of     :email
  validates                 :email, :email => true
  
  default_scope ->{ where(:account_id => Account.current_id) }
  
  belongs_to  :account
  embeds_many :phones, :cascade_callbacks => true
  embeds_many :urls,   :cascade_callbacks => true
  
  accepts_nested_attributes_for :phones, :urls, :allow_destroy => true
  
  def image_url=(url)
    unless url.to_s.empty?
      self.image = URI.parse(url)
    end
  end
  
  def image_url
    nil
  end
end

app/controllers/content/employees_controller.rb
class Content::EmployeesController < ApplicationController
  before_filter :authenticate
  
  def index
    @employees = Employee.asc(:index)
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @employee = Employee.find(params[:id])
    
    render
  end
  
  def new
    @employee = Employee.new(:account => current_account)
    
    render
  end
  
  def create
    @employee = Employee.new(params[:employee])
    
    if @employee.save
      track_activity @employee
      redirect_to content_employees_path, :notice => 'employee created successfully!'
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find_by(:id => params[:id])
    
    if @employee
      render :edit
    else
      redirect_to content_employees_path
    end
  end
  
  def update
    @employee = Employee.find_by(:id => params[:id])
    
    if @employee.update_attributes(params[:employee])
      track_activity @employee
      redirect_to edit_content_employee_path(@employee), :notice => 'employee updated successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    @employee = Employee.find_by(:id => params[:id])
    track_activity @employee
    @employee.destroy
    
    redirect_to content_employees_path, :notice => 'employee deleted successfully!'
  end
end

app/controllers/dashboard/activities_controller.rb
class Dashboard::ActivitiesController < ApplicationController
  before_filter :authenticate
  
  def index
    @activities = Activity.desc(:created_at).limit(15)
    
    respond_to do |format|
      format.html
    end
  end
end

app/views/dashboard/activities/employee/_create.html.haml
%span{:class => "info #{activity.trackable_type.underscore}"}
  = link_to raw("<em>#{activity.user.username}</em>"), account_user_path(activity.user)
  created
  = activity.trackable_type.downcase
  - unless activity.trackable.nil?
    = link_to activity.trackable.name, content_employee_path(activity.trackable)
  - else
    that has since been deleted
%span{:class => 'date'}
  = "#{time_ago_in_words(activity.created_at)} ago"

app/views/dashboard/activities/employee/_destroy.html.haml
%span{:class => "info #{activity.trackable_type.underscore}"}
  = link_to raw("<em>#{activity.user.username}</em>"), account_user_path(activity.user)
  deleted
  = activity.trackable_type.downcase
%span{:class => 'date'}
  = "#{time_ago_in_words(activity.created_at)} ago"

app/views/dashboard/activities/employee/_update.html.haml
%span{:class => "info #{activity.trackable_type.underscore}"}
  = link_to raw("<em>#{activity.user.username}</em>"), account_user_path(activity.user)
  updated
  = activity.trackable_type.downcase
  - unless activity.trackable.nil?
    = link_to activity.trackable.name, content_employee_path(activity.trackable)
  - else
    that has since been deleted
%span{:class => 'date'}
  = "#{time_ago_in_words(activity.created_at)} ago"